#lang htdp/bsl

(define-struct movie [title director year])
(define (a-movie movie)
  (... (movie-title movie) ...
       (movie-director movie) ...
       (movie-year movie) ...
       ))

(define-struct pet [name number])
(define (a-pet pet)
  (... (pet-name pet) ...
       (pet-number pet) ...
       ))

(define-struct CD [artist title price])
(define (a-CD CD)
  (... (CD-artist CD) ...
       (CD-title CD) ...
       (CD-price CD) ...
       ))

(define-struct sweater [material size color])
(define (a-sweater sweater)
  (... (sweater-material sweater) ...
       (sweater-size sweater) ...
       (sweater-color sweater) ...
       ))
